### ISSUE TITLE
Microsoft´s SmartScreen refuses to let me download latest version. 

### ISSUE THREAD

**Issue by therealtopgg** [DuoStream/Duo#102]
It is aparently detecting a virus, why is this happening?

**Comment by Black-Seraph** [comment]
Because we didn't fork over 500€ for a EV Code Signing Certificate and registered a separate legal entity with the Microsoft Hardware Developer dashboard.

There is no simple way around this other than manually allowing it.

See our Wiki's [known issues section](https://github.com/DuoStream/Duo/wiki/Known-Issues#antivirus-false-positives) for details.
