### ISSUE TITLE
Pen Pressure support?

### ISSUE THREAD

**Issue by NilouArmpits** [DuoStream/Duo#103]
Basically, I want to know if its possible if I could get tablet and pen pressure support, my art app says that It's using the mouse when I try their tablet tester, how do I do this?

**Comment by Black-Seraph** [comment]
@NilouArmpits What @samkitty said.

I am actually working on a Moonlight Android fork that adds pinch-to-zoom / rotate / palm-rejection and artist-type shortcuts to the app.

I'm using a Galaxy Tab S6 FE as a testing target for the pen pressure tests there.

The code for all of this will be published as part of the DuoStream organization on GitHub when everything is done.

tl;dr: Yes, Duo supports pen pressure, just like regular Sunshine does.

Issue closed.

**Comment by NilouArmpits** [comment]
It really doesn't work though, I'm using a XP Pen G640, a screenless art tablet and it gets treated like a mouse and yes my moonlight client is on linux

**Comment by samkitty** [comment]
> my moonlight client is on linux

Oh sorry I misspoke. Only Android and iOS builds of Moonlight support pen pressure. All versions of Moonlight have native 10 point multi-touch though. This is due to Moonlight-QT using SDL2 (input library) which does not expose pen data as per this [comment](https://github.com/moonlight-stream/moonlight-qt/issues/1247#issuecomment-2054168225) from one of the developers. SDL3 update will allow for pen support but that will take a while before it's ready for [stable release](https://github.com/libsdl-org/SDL/milestone/10).

Needless to say, this issue is unrelated to Duo and your only options for now are to either switch to an Android/iOS client or fork your own Moonlight build with SDL3.0 preview pen pressure implementation (see PR in thread above).
