### ISSUE TITLE
Will you consider open source sometime in the future?

### ISSUE THREAD

**Issue by lovelydumpling** [DuoStream/Duo#112]
From what I understand, this software does require a large degree of trust, for the things its able to do to your PC, for closed source software by a largely unknown entity. 

I think open source could largely assuage many security concerns because people would be able to know (or have faith others know) for sure everything the software is doing and capable of doing. 

I know right now, the unlocked version of this is a source of Patreon funds which might discourage opening the source (since people could then compile it for themselves), but if Yuzu's indication I think a lot of people would be willing to spend the money to not go through the trouble of compiling themselves. 

(I mainly bring this up not because I myself would know what to do with the source code but because I shared how cool this project was and the immediate response was security concerns from a closed source software.)

**Comment by Black-Seraph** [comment]
The actual RdpIdd.dll & IddCx.dll patching code is intentionally kept under wraps to add a certain degree of update resistance via security by obscurity.

I know that this is somewhat of a horrible approach, but it's kept Duo functional across countless Windows updates so far, out of which many targeted these two libraries, which makes me believe that this approach is somewhat sound and keeps us off Microsoft's radar just enough for them to not care.

The fact that we have to use a variety of loopholes to make Duo possible in the first place doesn't help and I really don't want to shine a big spotlight on that if I don't have to, given how few other options we have with modern Windows to reimplement these features otherwise.

What, IMO, triggers most AV software, is the fact that Memory Integrity has to be disabled to make Duo work.

This is typical behavior of malware, but also very much required for Duo so we can hijack the remote session's WUDFHost.exe process, which is a secure process hosted in Memory Integrity's hypervisor section, and thus, normally inaccessible to other programs running on the same computer.

This process hosts RdpIdd.dll, a DLL-based service responsible for spawning virtual monitors, which in turn loads and calls into the IddCx.dll interface which we hijack as part of the virtual monitor framebuffer capture process.

I am currently working on a framebuffer capture code re-implementation which hopes to wrap this service in a different fashion, one that won't require Memory Integrity to be disabled.

This will in no way fix the AV false positives though, as the presence of RdpWrap.dll itself is enough to trigger that already.

As for open-sourcing said parts of the code, I'd be willing to do it if I had some kind of guarantee that we could keep the functionality intact in full via a Microsoft-sanctioned way, but I doubt that will ever happen, especially with the way Microsoft is pushing for cloud-computing over local-premise installations.

**Comment by TomBayne** [comment]
> I know that this is somewhat of a horrible approach, but it's kept Duo functional across countless Windows updates so far, out of which many targeted these two libraries, which makes me believe that this approach is somewhat sound and keeps us off Microsoft's radar just enough for them to not care.

Out of interest - would Microsoft actually care about people patching in multi-seat? I'm not convinced this project is big enough for them to care. They haven't done anything about people building other multi-seat software yet (Aster, etc.). They have their own MultiPoint Services, so breaking your multi-seat would likely break that too.

> I'd be willing to do it if I had some kind of guarantee that we could keep the functionality intact in full via a Microsoft-sanctioned way, but I doubt that will ever happen, especially with the way Microsoft is pushing for cloud-computing over local-premise installations.

Could you utilize Multi-Point services in some way to do this in a 'Sanctioned' way? I know its Windows Server functionality but maybe the functionality could be unlocked within workstation version of Windows through some method?

**Comment by Black-Seraph** [comment]
> Could you utilize Multi-Point services in some way to do this in a 'Sanctioned' way? I know its Windows Server functionality but maybe the functionality could be unlocked within workstation version of Windows through some method?
I have no doubt we could go that route but how is that any more sanctioned than the current implementation? 

It still requires policy patching to enable hidden functionality without a true guarantee to remain 100% functional. 

Or am I missing something?

**Comment by TomBayne** [comment]
> > Could you utilize Multi-Point services in some way to do this in a 'Sanctioned' way? I know its Windows Server functionality but maybe the functionality could be unlocked within workstation version of Windows through some method?
> > I have no doubt we could go that route but how is that any more sanctioned than the current implementation?
> 
> It still requires policy patching to enable hidden functionality without a true guarantee to remain 100% functional.
> 
> Or am I missing something?

I don't think it requires any policy patching on a Windows Server instance. Not sure how it would work on a consumer Windows version - don't have the spare hardware to test on either :(

**Comment by loyejaotdiqr47123** [comment]
__

> 实际上，RdpIdd.dll 和 IddCx.dll 的补丁代码是故意保密的，以通过“隐蔽性安全”增加一定的更新抵抗能力。
> 
> 我知道这种方法有点糟糕，但它在无数个Windows更新中一直让Duo保持正常运行，其中许多都针对这两个库，这让我相信这种方法在某种程度上是可行的，足以让我们避开微软的视线，以至于他们不会在乎。
> 
> 我们不得不使用各种漏洞来实现Duo，这本身就很令人沮丧，而且考虑到在现代Windows中，我们几乎没有其他选择来重新实现这些功能，所以我真的不想对此大肆宣传。
> 
> 在我看来，导致大多数AV软件触发警报的原因是，为了使Duo工作，必须禁用内存完整性功能。
> 
> 这是恶意软件典型的行为，但对于Duo来说也是非常必要的，这样我们就可以劫持远程会话的WUDFHost.exe进程，该进程是一个安全进程，由Memory Integrity的虚拟机管理程序部分托管，因此通常对其他在同一台计算机上运行的程序不可用。
> 
> 这个过程会加载并调用RdpIdd.dll文件，这是一个基于DLL的服务，负责创建虚拟监视器。随后，该服务会加载并调用IddCx.dll接口，我们将该接口作为虚拟监视器帧缓冲区捕获过程的一部分进行劫持。
> 
> 我目前正在编写一个帧缓冲区捕获代码的重新实现版本，希望能够以一种不同的方式实现该服务，这样就不需要禁用内存完整性了。
> 
> 然而，这并不能解决AV软件的误报问题，因为只要系统中存在RdpWrap.dll文件，就会触发误报。
> 
> 至于将代码的部分部分开源，如果我们能保证通过微软认可的方式完整地保留其功能，我愿意这样做，但我怀疑这种情况永远不会发生，尤其是在微软大力推动云端计算而非本地安装的情况下。

[https://github.com/llccd/TermWrap](https://github.com/llccd/TermWrap)
You can use termwrap instead of rdpwrap.
And it doesn't need to rely on the ini file like rdpwrap does, which means there's no need to keep updating rdpwrap.ini.

**Comment by Black-Seraph** [comment]
TermWrap has been implemented as of version 1.4.6, alongside with a new wrapped DuoIdd driver that wraps RdpIdd & IddCx to enable frame capture without the need for having Memory Isolation disabled.
