### ISSUE TITLE
Source?

### ISSUE THREAD

**Issue by OhaDerErste** [DuoStream/Duo#120]
![8qqo7p](https://github.com/DuoStream/Duo/assets/77100649/014f8977-8ce0-4370-ada2-6c36c6f39094)

**Comment by Black-Seraph** [comment]
All the GPL licensed components can be found in the [DuoStream organization](https://github.com/orgs/DuoStream/repositories).

**Comment by p0358** [comment]
@Black-Seraph This is in violation of GPL, see:

- https://www.gnu.org/licenses/gpl-faq.en.html#GPLInProprietarySystem
- https://www.gnu.org/licenses/gpl-faq.en.html#GPLPlugins
- https://www.gnu.org/licenses/gpl-faq.en.html#GPLAndPlugins

The included software effectively constitutes a single combined program with your proprietary parts, they're distributed in a single package and work together, therefore it's all covered by GPL.

As such, you must release all of the source code of Duo, under the GPL or a GPL-compatible free software license.

**Comment by BTFighter** [comment]
I second this.

But they're just going to sweep this under the rug, as usual.

**Comment by VelocityRa** [comment]
Pinging: @ReenigneArcher @cgutman @ns6089 @TheElixZammuto. Please see above.

**Comment by ReenigneArcher** [comment]
Well, I am not a lawyer, but my opinion is that yes this is in violation the license of Sunshine. Since Duo could not exist without Sunshine, then in my opinion the entire product must also be licensed the same as Sunshine.

I don't think requesting a DMCA takedown with GitHub would solve anything though, as it would just remove this empty repository which doesn't even contain any source code.

**Comment by VelocityRa** [comment]
It seems there's a misunderstanding of a core concern here (beyond security).
I don't care about protecting companies or the GPL, I have my share of criticisms of  it and project using it.

As it stands, the [bus factor](https://en.wikipedia.org/wiki/Bus_factor) for this project is 1. When (not if) the sole maintainer stops building this for any reason, the project **dies**.
If the code were at least available, people such as myself could pick up the torch (this happens very often) without having to duplicate hundreds to probably thousands of hours of work.

The fact that this has an active community vested and interested in it should be even _more_ of a reason to want it to survive beyond a single contributor.

I respect and appreciate the massive amount of work that has been put into this by @Black-Seraph - much of it 'invisible' eg. reverse-engineering Windows components I'm sure. I would gladly pay to support it even if the source was available, just like I do for other projects that do just fine with that model. I just want to ensure it survives and thrives further.
The extra features and fixes from said community it would likely receive if open-sourced (instead of just source-available) would just be a nice bonus. :)

**Comment by dacampsss** [comment]
As @ns6089 said here, GPL is not about developers being not able to charge for full features, it's only about the freedoms to use, to inspect code, to redistribute, to remix. I see the problem here, on a full source code being a possible way to illegally "unlock" the software. That said, not any end user would be able to analyze and build a custom version to circumvent the pay restriction. Good software can use tokens, crypto and other mechanisms to make things difficult for crackers. Closing this issue is not a good behavior, cause project here is clearly violating GPL. If Sunshine devs chosen GPL, I see that the reason can possibly be not only to avoid charging for software, but also thinking in privacy and posterity, in a future when the main dev can simply abandon the project. And if the devs of the forked code made this decision, it should be respected. Copyleft is about freedom and philosophically admitting that knowledge is *always* collective, it's always built shoulder by shoulder. It's the license that mostly enforce a Commons perspective. Duo seem to be magic, but also Sunshine is doing the difference here, being the base for Apollo, for Vibeshine and Vibepollo, all being excellent software that are respecting GPL, enabling an entire chain of useful and amazing tools for users and for the dev community.

Ps.: if Sunshine were licensed as LGPL, and not GPL, _then_ and _only then_ this project would be respecting Sunshine license. It happens cause LGPL do assume that the product is a library, and as library, only its modified parts could be published, exactly how it's being done here. However, full GPL states its product as the _entire finished product_, so derivatives must be also GPL.

Ps. 2: the software itself is nice, I'm using the free version and thinking of contributing to unlock the full features. I'd still think the project should respect GPL.
