### ISSUE TITLE
“ This game can not be run on a remote desktop instance “

### ISSUE THREAD

**Issue by IamBobble** [DuoStream/Duo#139]
When running Black ops 3, i get the error message. Is there anyway to bypass this. Seems the issue is the game detecting the instance as an RDP instance and therefore preventing launch.

**Comment by Black-Seraph** [comment]
I don't own Black Ops 3 so I can't give you a definite answer, but there's a handful of methods to detect remote sessions.

- int GetSystemMetrics(SM_REMOTESESSION) (in user32.dll, [documentation](https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getsystemmetrics))
- int RtlGetActiveConsoleId() (in ntdll.dll, undocumented)
- ActiveConsoleId (in [KUSER_SHARED_DATA](https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/ntddk/ns-ntddk-kuser_shared_data))

GetSystemMetrics internally calls RtlGetActiveConsoleId, which in turn reads the ActiveConsoleId from the KUSER_SHARED_DATA structure exposed by the Windows kernel.

This issue could be circumvented on a per-game basis by...

- Patching the game binaries
- Swapping in a custom user32.dll that patches GetSystemMetrics
- Swapping in a custom ntdll.dll that patches RtlGetActiveConsoleId

Or globally by...
- Writing a custom kernel driver that patches KUSER_SHARED_DATA (expensive and very unlikely because of Microsoft's strict driver signature requirements)

The sad thing is that all of this isn't difficult to fix, but Anti-Cheat systems out there have become so draconic that even the smallest library patches are picked up as potential cheating attempts now, rendering the "easy fix" useless.

**Comment by IamBobble** [comment]
i saw an old post of yours and took the liberty to learn and made my own dll to inject into the game and it works, if anyone wants the code idm sharing it. but Bo3 runs without the dll if u use boii client. 

Regardless, thank you and i’ll prob look into those other methods as they seem more permenant than my current sketchy injecting DLL file method.

**Comment by Black-Seraph** [comment]
Your best bet at implementing this without having to touch the kernel is to hook RtlGetActiveConsoleId() in ntdll.dll and force it to return the SessionId returned from [ProcessIdToSessionId](https://learn.microsoft.com/en-us/windows/win32/api/processthreadsapi/nf-processthreadsapi-processidtosessionid).

This way the game will always see the remote session as a console session.

**Comment by IamBobble** [comment]
would that require dll injection into the game? or would it be a temporary thing i do for when i launch the game?

**Comment by Black-Seraph** [comment]
There's several ways you can inject code into the game.

The best one, IMO, would be to write a ntdll.dll wrapper library that features identical exports and passes them through to the real ntdll.dll, while also patching the RtlGetActiveConsoleId return value.

Another one would be to write a remote process injector plus a small Minhook-based library that contains the RtlGetActiveConsoleId hook.

That way you could then hook the game process' ntdll.dll copy in RAM, but it would require a separate .exe file to do the injection, while the first approach means people can just copy the patched ntdll.dll into the game's installation directory.
