### ISSUE TITLE
SignalRGB Opening/Closing

### ISSUE THREAD

**Issue by lunar-studio** [DuoStream/Duo#142]
Not sure if there’s anything you can do about this, but logging in from a remote device, I noticed the Win 11 host desktop will repeatedly open and close SignalRGB. It was happening so fast that I couldn’t even find it in the processes and had to record it on my phone then play it back in slow motion. I ended up uninstalling it.

**Comment by Black-Seraph** [comment]
My guess is that you probably have it set up to start as part of a user logon rather than system start, that would explain multiple instances of the same service type application, but your guess is as good as mine, I don't really use SignalRGB so I wouldn't know.

Either way, this is a environmental thing that Duo can't really control.

It's not Duo's job to administrate the applications running on your computer and I can't really implement anything like this in good faith either as it would be way too invasive IMO.
