### ISSUE TITLE
Tekken 7 weird resolution

### ISSUE THREAD

**Issue by AmplificPanda** [DuoStream/Duo#148]
Launched tekken 7 via Steam Big Picture mode, resolution on moonlight is set to 4K 60 fps, Duo is patreon version. The game launches fine, but the game does not fit on the screen in full screen mode. It goes off the screen completely.

Is there a fix for this kind of issue? 

The normal sunshine client does not have this issue.

**Comment by samkitty** [comment]
right-click on the game's .exe file, select **Properties**, and then go to the **Compatibility** tab. Click on the checkbox **Override high DPI scaling behavior.** and from the dropdown menu choose **Application**.

You might want to **Change settings for all users**.

**Comment by AmplificPanda** [comment]
This fixed it. The only issue that now remains is the playnite being laggy + I cant get my microsoft signed in user to work at all

**Comment by Black-Seraph** [comment]
Not much I can do about the Microsoft Sign-In stuff just yet, but I'm experimenting with a few undocumented Windows APIs to directly spawn user sessions rather than going through the RDP stack which might help with the number of available authentication methods.

If that works we can drop the whole NTLM requirement, which would solve that issue as well.

No promises though as there's still a lot to be done on that part.

As for Playnite being laggy, that thing lags the exact same even on a console session for me, which makes me believe this might be related to multi-GPU systems more than Duo, but with a sample size of 1 local Playnite install I don't quite trust that assumption either.

Call it a hunch.
