### ISSUE TITLE
Starting control stream establishment failed (On local or on WAN)

### ISSUE THREAD

**Issue by MarshyMadness** [DuoStream/Duo#185]
It stalls out at Control Stream Establishment and spits out error -2 usually says port 47999 blocked but I opened that one and all the ones required for the stream (the specific ones shown in sunshine UI) for both the Router and my Firewall. It refuses to connect and this problem only occurs when Hosting from one PC, the other host everything works fine but no device can connect to this instance. The weirdest part is it works on a different user but not on the other one. So it works fine on Helen but not on Justin.
![parsecd_6UnHjymSI3](https://github.com/user-attachments/assets/713c9621-821b-4543-9925-e6c302ea5633)

**Comment by Zedlayne** [comment]
@altano, I presume you are experiencing this issue with the new version 1.5.3? I am getting that error as well, but only occasionally

**Comment by altano** [comment]
Yep, 1.5.3. My client connects fine but my friend is getting that error.

We figured it out though: I hadn't forwarded the right UDP ports in Tailscale (which is why I could connect but my friend on WAN couldn't).

Duo will give you the primary TCP port for Moonlight, but you have to go into the Sunshine Configuration -> Network page and add all the ports found there to your Tailscale control policy.
