### ISSUE TITLE
patreon version 1.4.9 not creating program directory after install

### ISSUE THREAD

**Issue by patrickRx** [DuoStream/Duo#203]
Hello, I'm installing duostream for the first time, version 1.4.9.0 patreon. I'm on Windows 11 24H2. The install completes and prompts me to reboot. However, there's nothing installed in the Program Files directory. I'm unable to locate Duo Manager in the start menu. I'm unsure how to troubleshoot this. Thanks.

**Comment by dr0g0007** [comment]
Hi, exactly what 1.4.9.0 does on mine as well, tried a couple of times and Duo-Manger isn't installed, tried previous two earlier versions, installs and you can get to run Duo-Manager, but the service starts and stops, maybe due to me having a Microsoft account as it states within troubleshooting to have a local account. Very frustrating , as Moonlight and Sunshine work amazingly well on my setup and over the internet .. I just wanted to run a few instances of sunshine for my friends etc. .

**Comment by patrickRx** [comment]
I'm assuming it has something to do with the pinned issue #165, although it's not clear to me there's a workaround at this time.

**Comment by patrickRx** [comment]
closing as duplicate of #202
