### ISSUE TITLE
With the HDR feature enabled framerate is bad

### ISSUE THREAD

**Issue by Gammler** [DuoStream/Duo#28]
Hello,

i have the problem with the update for HDR what i simple can't enable HDR in DUO Manager regardless of streaming client, without having a low framerate like 20-28 FPS with 3840x2160 resolution. It is solved with 1080p or lower. (with 1440p sunshine doesn't start at all)

I am confused about this, because i can stream 4K HDR without any problem without DUO with sunshine itself on my 3090. I am debugging this shit since the v1.2.0 now. Any suggestions?

**Comment by Black-Seraph** [comment]
Duo works via shared memory framebuffers, which is needed to reliably capture swapchain frames in a multi-session environment, where DXGI duplication is unavailable.

As such the performance overhead grows with the physical size the framebuffer occupies in memory.

The size the framebuffer occupies is calculated from the width x height x bytes per pixel.

A SDR image would thus consume 3840 x 2160 x 4 bytes in memory, following your example.

An HDR image would consume twice that amount because a single pixel is represented as a 8 byte (64bit) high precision value with 2 bytes (16bit) precision per color component.

We're quite literally reaching the point where shared framebuffer mirror implementations reach a point of failure.

I hope to reduce that overhead sometime in the future by forcing the HDR framebuffer into a 10bit per color component mode, but so far haven't found a working combination of IddCx flags to do so, which is why HDR currently uses 16bit precision, causing the performance loss you've encountered.

Once I find a way to toggle 10bit per color component precision, the performance should be identical to running an SDR instance.

**Comment by Black-Seraph** [comment]
The issue I have with 10bit precision is that IddCx drivers roll a 16bit precision buffer internally, regardless of which precision I configure them to run in.

Looking at Sunshine reference source code, I don't even see any handling for native 10bit precision buffers, which makes me believe that Windows might be rolling 16bit precision buffers for everything internally.

If that is the case then that would make this issue unsolvable without finding a suitable alternative capture method.

Time will tell.

**Comment by Black-Seraph** [comment]
I've taken a closer look at the inner workings of the RdpIdd driver and discovered that the monitor's swapchain texture is created as a shared resource, which means I should be able to derive an NT-handle from it and use it directly, cutting away a lot of the per-frame overhead.

If this works out the way I hope it does we'd be looking at a capture performance increase of 100%~150%, which should be plenty headroom to make HDR work nicely at higher resolutions and open the door to > 90Hz 4K SDR capture.

**Comment by Black-Seraph** [comment]
Fixed in version 1.2.2.

**Comment by Gammler** [comment]
Are you sure about the latest changes? Now i get a bad framerate no matter what mode, SDR or HDR, no matter what client. No matter what profile. I also get some weird checkerboard flickering sometimes. I will check again later today when i have more time.

**Comment by Gammler** [comment]
Thanks for the 1.2.3 update. It is now finally fixed. I noticed it the second my Steam BPM did the boot animation.
