### ISSUE TITLE
Sunshine Applications List is duplicated across instances

### ISSUE THREAD

**Issue by gattostivalato** [DuoStream/Duo#32]
Despite only adding a specific game to Session A's Sunshine control panel, the same exact game, path, arguments and game's PNG icon are also visible in Session B's Moonlight view. 

Checking Session B's Sunshine control panel, I can see the game I created for Session A in the Applications list. 

https://github.com/DuoStream/Duo/assets/126280868/d74b8f2c-0add-4611-846a-d08759c2bc86

**Comment by Black-Seraph** [comment]
This was / is intentional, as setting custom app lists for each session only partially works with the underlying Sunshine code base, without fully duplicating the Sunshine installation directory that is.

It's one of those leftover to-dos that depends on Sunshine to fix one of their own bugs first, and I figured I'd just wait this one out until they do.

I will leave this issue open though, as it is valid, and needs to be addressed eventually, in one form or another.

**Comment by Gammler** [comment]
I just want to add, that this might be also prefered in some scenarious to be honest, for example because of the SDR / HDR limitations right now i am using the same application set between those profiles which makes it easier for me. Also for my steam deck i don't need to add them as well, but a downside is that i can't remove single applications then. An option to hide applications is still possible on android but not windows/linux unfortunately.

But to be honesti don't see that as a real problem right now. I would really pefer a better duo manager or control panel first that is a little bit more communicative. Like running version, logs etc. and also being able to disable/enable specific streaming profiles, reboot single instances instead of all. If you want i can still open seperate feature request(s) for this.

**Comment by Black-Seraph** [comment]
I agree that per-instance controls would be very useful to have, but let's keep these issues separate so they can be discussed properly.

Feel free to create issues as needed.

**Comment by Black-Seraph** [comment]
Fixed as of version 1.2.8.
Issue closed.
