### ISSUE TITLE
RDP 'Fullscreen' support

### ISSUE THREAD

**Issue by StijnWolf** [DuoStream/Duo#39]
Hey, I firstly want to thank you for this great tool because it's very useful to me. 

I often dock my Steam Deck OLED to my TV so I'd like the RDP session's resolution to match my client's resolution. (I stream at 1080p@120hz btw). I tried setting the width and height to 0 but that's invalid input. I'd like the virtual monitor's resolution to be 1280x800 when using the Deck in handheld mode and 1080p when docking to an external monitor. 

Is there a built in way to set a profile's resolution to 'fullscreen' like with mstsc?
Does Duo.exe have access to sunshine's shell variables given by the moonlight client? I'm referring to the values such as 
SUNSHINE_CLIENT_WIDTH, SUNSHINE_CLIENT_HEIGHT and SUNSHINE_CLIENT_FPS?

I wouldn't mind having to automate a part of this myself by editing the profile's configuration before the Duo.exe launches but I can't find where the profile's resolution width and height are stored locally.

**Comment by Black-Seraph** [comment]
Remote session display drivers work a little bit differently than their console session counterparts.

There's many differences, but the one that pulls weight here is that a remote session display drivers don't officially support target mode changes.

A target mode is a combination of display width, height, refresh rate, bit depth and color mode.
For example 1280x800@90Hz with 10bit per color component and HDR10 color mode.

This target mode has to be set BEFORE the session is established, which happens when Duo starts it, and while there are ways to change the target mode while the session is running, this can only happen from within the driver itself, as all display-related APIs are stubbed out while inside of a remote session.

This means that we need to implement a way to RPC into the monitor driver first so that Sunshine's RTSP backend can issue on-demand target mode changes.

This feature is already being worked on and will, eventually, replace the current per-instance width, height, refresh rate, scale and color mode settings, giving full control of these to the respective Moonlight client.

Due to the complexity involved there is nothing a regular, or even crafty, user could script together to work around this, which means that you'd have to create two instances in the meantime.

One aimed at your docked use, and another aimed at your portable use scenario.

**Comment by StijnWolf** [comment]
Your placeholder solution will be perfectly fine for now, but it's really good to hear this issue has already been thought about. I understand that the order of operations makes this difficult to implement.
 
 Thank you for your detailed answer!

**Comment by Black-Seraph** [comment]
Constructive criticism is always welcome here.

It will be a bit until this is fully implemented, but once it is, all Duo instance will adapt to fit the settings the Moonlight client requests via RTSP.

A true one-stop solution that can service a whole family, or an array of devices, if needed, powered by a single host system.

**Comment by Black-Seraph** [comment]
Version 1.2.9 implements this enhancement, handing full control of resolution, refresh rate, scaling and dynamic range, over to Moonlight.

Issue closed.
