### ISSUE TITLE
"This application cannot be run on remote desktop"

### ISSUE THREAD

**Issue by NilouArmpits** [DuoStream/Duo#50]
Is there a possible way to fix this? I know that when I connect through moonlight the session has some kind of "RDP" marked into it, is there any way to spoof/fix this?

**Comment by Black-Seraph** [comment]
One could hook the GetSystemMetrics function inside the to-be-spoofed application and return false when the caller queries for SM_REMOTESESSION.

Duo doesn't do this automatically though, as this would trigger several anti-cheat systems and break more games than it would fix.

I will close this issue and mark it as **wontfix** due to anti-cheat being in our way of implementing this, despite it being very much possible to do so.
