### ISSUE TITLE
v1.3.4 Steam multi-instance not working with Playnite

### ISSUE THREAD

**Issue by samkitty** [DuoStream/Duo#57]
Using Playnite in Fullscreen mode on host PC causes one of the 2 Steam instances to shut down after launching a game. This doesn't happen ~~in Desktop mode or~~ when using Steam directly to launch the games.

Host PC = Playnite Fullscreen + Steam Instance 1
Client PC = Steam Big Picture + Steam Instance 2
Launch game on host PC through Playnite Fullscreen > Steam instance 1 or 2 (or both!) will say "shutting down Steam"

I am using the patreon version, build 1.3.4

Can anyone reproduce? Any clues on why this might be happening?

Using either the built-in Steam Big Picture shortcut or the -master_ipc_name_override launch argument  on both host/client doesn't make a difference.

**Comment by Black-Seraph** [comment]
Are you starting Steam Instance 1 via a suitable batch file to boot Steam into it's multi instance mode?

Try doing that first and see if that solves the problem.

See #48.

I can't really say all too much about Playnite because I don't use it, but my guess is that it's an issue with your physical Steam Instance running in normal mode.

**Comment by samkitty** [comment]
Yes, I tried starting Steam in multi-instance mode manually as well as via the Steam Launcher Utility (plugin that allows you to specify launch arguments for Steam games through Playnite). No real difference, launching games through Playnite closes one of the 2 Steam instances. In fact, Playnite isn't working at all with multi-instance Steam in both fullscreen as well as desktop mode.

![image](https://github.com/DuoStream/Duo/assets/57629730/58f3682b-8338-40c8-8f64-e2f4c4439bef)

I realize this isn't Duo's fault and you won't be able to help much since you don't use Playnite yourself, I was hoping other Playnite/Duo users (like @XexuWilder) might have a clue.

**Comment by Black-Seraph** [comment]
Duo does its best to give users 90% of what commercial grade vGPU hardware would give you, but does it in software on consumer grade hardware to make it affordable.

Mix that with Steam's not-yet-default multi-instance mode, sprinkled with third-party launchers that aren't even aware such a mode exists, and things are almost guaranteed to break somewhere.

I do agree with your opinion that this issue should be addressed in Playnite though, and here's why:

Steam's multi-instance mode will become the standard at some point, and implementing support for it early, when such an option exists, should be in Playnite's best interest.

That aside, I wouldn't even know how to best implement a fix for this on Duo's side anyway.

Playnite is its own software and there's very little Duo can do to influence its behavior.

This is in line with issue #33, where external software is messing up but somehow people still think it should be fixed on Duo's side, simply because Duo makes the issue apparent.

**Comment by samkitty** [comment]
Mhm, I fully agree with you, I've been using DUO for 2 days and I'm quite impressed so far by how much you've achieved through software only.

I will do some more debugging to craft a proper bug report on this issue then discuss it with the folks at Playnite. I'll keep you updated in case I find a solution in the meanwhile so that you can add it to your wiki if you choose to.

I've gone ahead and closed this issue for now.

Cheers ᵔ⤙ᵔ
