### ISSUE TITLE
5.1 Remote audio issue

### ISSUE THREAD

**Issue by XexuWilder** [DuoStream/Duo#73]
Hi!

I'm not getting 5.1 audio inside games when I use android sunshine client and configuring it on both sides, sunshine and duo stream.

I'm not sure if the problem is the virtual sink audio configuration, when I open the admin console of duo stream over virtual sink appears "Remote Audio" (note from that option says "We strongly recommend leaving this field blank to use automatic device selection!")

When I connect the stream if I go to sound settings, it appears right and left volume, but I can't see any other settings for this.

A strange behavior is the option "Install Steam Audio Drivers", is disabled by default and I can change to enable, but when I do that it doesn't save if the PC restart, only if you restart duo service right after the change.

I'm not sure if I would need to change the default Virutal sink to "Steam Streaming Speakers" maybe?

The most strange thing is when I connect to the stream my AV receiver says is a 5.1 PCM audio but the host is just sending stereo.

Not sure where is the problem...

Thank you!!

Using:

-Windows 11 duo stream 1.3.7+ (patreon)
-Running big picture steam shorcut from duo

As client:
-Android TV (nvidia shield) moonlight

**Comment by Black-Seraph** [comment]
Duo uses a variety of Microsoft's own virtual device drivers to get things done, mostly because we can't sign our own drivers to meet the Windows 11 signature requirements.

What you're experiencing is a driver limitation in Microsoft's virtual sound card driver.

I'll update the known issues section to include this information and close this issue for the time being.
