### ISSUE TITLE
Resolution Issue

### ISSUE THREAD

**Issue by bwinyu** [DuoStream/Duo#91]
Hi, I am trying to use Duo but having some issues getting my screen resolution to 1080p. I have it set as 1080p on Moonlight. Lower resolutions work (eg. 720p, 480p) but when I set it to 1080p it sets the resolution to 1536 x 864 (seems like it’s auto scaling to 125% even though I have it set to 100% on Duo).

I am on Windows 11 23H2.

**Comment by Black-Seraph** [comment]
Could you please attach an export of your application event log and a copy of your running instance's log file?

You can find your instance's log files in **C:\Program Files\Duo\config**.

The file in question should be named **<YourInstanceName>.log**.

**Comment by bwinyu** [comment]
[bwin.log](https://github.com/DuoStream/Duo/files/14889416/bwin.log)
[application event log.zip](https://github.com/DuoStream/Duo/files/14889489/application.event.log.zip)

Not sure if these are the right files, let me know if you need anything else.

Thanks!

**Comment by Black-Seraph** [comment]
Can you connect to your instance via Moonlight and re-upload the bwin.log file as it is while you're connected?

**Comment by bwinyu** [comment]
[bwin.log](https://github.com/DuoStream/Duo/files/14889660/bwin.log)

**Comment by Black-Seraph** [comment]
It seems like your logs are all in order.

Mind telling me where this issue actually shows itself and how you come to the conclusion that something isn't functioning as it should?

The scale factor in Duo is calculated from the resolution that Moonlight requests via RTSP, with a baseline of 100% at 720p, scaling up to 300% at 4K.

The slider in the instance tab only lets you apply a scale factor on top of that dynamically calculated one.

**Comment by bwinyu** [comment]
Yeah, I'm trying to run 1920x1080 but it's resizing to 1536x864. Like you said, in 720p it has the correct resolution. Is there no way to have it 1920x1080 in 100% scale?

1080p
![image](https://github.com/DuoStream/Duo/assets/16823489/ea7ae17d-0270-4d89-8456-841dc2645b2b)

720p
![image](https://github.com/DuoStream/Duo/assets/16823489/305955dd-2abd-4cbe-b649-0baf88b97bb8)

**Comment by Black-Seraph** [comment]
Browser-based tests **never** return the correct resolution on sessions that aren't set to 100%-scale, unless the browser itself is aware of scale factors and handles them properly.

This is normal and happens even on console sessions at anything but 100%-scale.

Summed up: Your setup works as it should, but your browser doesn't know what scale factors are and thus gives you the resolution of its internal viewport.

1080p streams clock in at a default scale value of 125% because the baseline is calculated from a range of 100% at 720p and 300% at 4K.

This is done because Moonlight itself doesn't report client device screen metrics, which means we need to rely on guesswork to set somewhat sane defaults.

My proposed solution is to adjust Duo Manager's scale factor adjustment range from 100-200% to 50-200%.

This should allow you to manually set a adjustment of 80% for your instance, which should yield you a 100% scale factor for 1080p sessions.

**Comment by bwinyu** [comment]
I see, that sounds like the perfect solution. Is that something I can manually adjust on my side or do I need to wait for you to do it for the next version of Duo?

Thanks so much for your help!

**Comment by Black-Seraph** [comment]
> I see, that sounds like the perfect solution. Is that something I can manually adjust on my side or do I need to wait for you to do it for the next version of Duo?
> 
> Thanks so much for your help!

I'm on it already.

Expect a version 1.4.2 update within the next 30 minutes or so that will address and close this issue.

**Comment by Black-Seraph** [comment]
Version 1.4.2 is now live.

@bwinyu You should now be able to set your scale factor adjustment value to 66% and achieve the 1080p@100% scale result you wanted.
