### ISSUE TITLE
Unable to force a specific encoder.

### ISSUE THREAD

**Issue by therealtopgg** [DuoStream/Duo#96]
Just bought the paid version of Duo, having tryed the free one a couple of months ago. When I first tryed it out, I was able to make Quicksync my encoder while having an AMD gpu as my main one for display and render but, for some reason Im unaware of, I cant do this anymore. I have an Intel I5 11600K and an RX 6700xt. Running latest windows 11 updates.

Edit: Intel Quicksync is selected as an encoder in the "Advanced" sunshine tab.

**Comment by Black-Seraph** [comment]
This is because version 1.2.2 and newer capture their framebuffer via NT shared handles, while versions prior copied the framebuffer into a intermediary texture.

NT shared handles are a lot faster, giving us better capture performance and thus enabling us to reliably provide 4K+ resolution streams, but they come at the cost of having to encode them on the GPU they were rendered on.

Because of this limitation Duo now picks the strongest GPU in the system, sets it as the default render adapter in termsrv.dll, which forces Sunshine to use a hardware encoder that matches the chosen GPU.

This is expected and wanted behavior. Everything else would result in subpar performance.
