### ISSUE TITLE
Remote session is frozen after host sleep and requires a restart

### ISSUE THREAD

**Issue by kopiezzo** [DuoStream/Duo#97]
Hey, I have another problem but I hope this is the last one. Specifically, after the computer is in sleep mode for a longer period, the remote session freezes. Upon connection, I can see the desktop but I can't move the mouse, and in the Task Manager, "Windows driver foundation" is at the top (screenshot below). Restarting the host or simply restarting the session using Duo Manager usually helps but if im away and im using WOL to wake up PC i can't connect to restart it.

I'm trying to find some clues in the Event Viewer but the only thing I'm finding is:
`EventData 
  AppName sunshine.exe 
  AppVersion 0.22.2.0 
  AppTimeStamp 6608b74c 
  ModuleName KERNELBASE.dll 
  ModuleVersion 10.0.22621.3374 
  ModuleTimeStamp 3069ce37 
  ExceptionCode 80000003 
  FaultingOffset 000000000010cf22 
  ProcessId 0x6ad0 
  ProcessCreationTime 0x1da8ab1d99f8953 
  AppPath C:\Program Files\Duo\sunshine.exe 
  ModulePath C:\Windows\System32\KERNELBASE.dll 
  IntegratorReportId 9d84eb66-29ac-4248-9cea-ee22c7bf76a0 
  PackageFullName  
  PackageRelativeAppId`
  
  Sunshine log seems fine. Screenshot is not mine but I see the same
  
  
![wudfhost-exe-2](https://github.com/DuoStream/Duo/assets/15052907/2745c084-9b38-48cd-8fc7-321166b24d07)

My CPU is Ryzen 5600x, GPU: RTX 4070

Edit: after googling a bit i've decided to do a clean Windows install and will report after that

**Comment by kopiezzo** [comment]
Seems like disabling XMP profile on RAM fixes the issue, i will reopen if not, sorry for the fuss

**Comment by kopiezzo** [comment]
Well, sadly, I still experience this issue, which did not occur with the standard Sunshine build. After sleep, my GPU crashes (I suppose) and throws: "\Device\Video3 Error occurred on GPUID: 600" errors, resulting in high CPU usage by WUDFHOST:

![asd2](https://github.com/DuoStream/Duo/assets/15052907/f5ce9953-51d0-49e7-a2f2-748c671878cd)

Sometimes the sessions freeze, sometimes not. Also, after this happens, whenever the PC is put to sleep and then awakened, my monitor does not turn on until I move my mouse (which does not happen if Duo is turned off before the sleep and crash).

**Comment by kopiezzo** [comment]
> I have this exact issue. I've written a very basic Powershell script that restarts the Duo service only if the service was already running. I've then set up a task in Task Scheduler that runs this script when waking from sleep, which does add a delay to getting Duo working, but does the trick for now.
> 
> Let me know if you want more details or the script.

You can try disabling HAGS; it seems like it helped me a bit, but I'm still testing. If it's not working still, I'd be grateful for the script. Though I'd like to keep HAGS enabled in the future because of frame generation.

**Comment by Black-Seraph** [comment]
If I had to guess its probably related to a GPU driver crash that causes the display surface NT handle to become invalid.

That's the equivalent of unplugging the instance's monitor cable.

I personally haven't encountered this issue yet, but I do run a NVIDIA GPU myself, so maybe I can recreate the issue on one of my test machines.

@kopiezzo @bigjam3 I'm sure we can mitigate this issue somewhat. I will keep you two posted.

**Comment by Black-Seraph** [comment]
Talking about HAGS, it has several downsides actually, some of which Duo actively works around.

When HAGS is enabled then nvenc starts behaving somewhat erratic, or rather, unresponsive.

It won't react in a timely fashion to client requests, what normally takes 1-2 seconds now takes 30 seconds, etc.

This is why Duo's fork of Sunshine upped the wait limit from 10 to 30 seconds to ensure active streams can be closed without having to restart the Sunshine instance.

I personally wouldn't be surprised if HAGS was the cause of this issue, but without further evidence I wouldn't dare point fingers just yet.

**Comment by Black-Seraph** [comment]
@bigjam3 @kopiezzo Please try the newly released 1.4.4 build and see if this issue still persists.

**Comment by Black-Seraph** [comment]
This is the world we live in.

We can't make changes to NVIDIA's drivers so all we can do is mitigate.

I'm not entirely sure I understand what you mean by "session is not running immediately and it closes" though. 

Moonlight doesn't let you connect before the instance is live anyway.

**Comment by kopiezzo** [comment]
Sorry, you are correct. The error was something else; it just takes a bit longer to connect. I've started seeing a black screen unless I move my mouse after connection on version 1.4.4. Could this be a bug?

> Instances now pause whenever the host suspends.

Would it be possible to make this option a toggle in Duo settings? I will start testing with HAGS enabled today.

**Comment by Black-Seraph** [comment]
@kopiezzo The "black screen" issue isn't directly caused by Duo but rather dwm.exe's internal refresh rate.

Let me explain:

When Windows sits idle on the Desktop, or any other window it considers idle, it will lower its internal refresh rate to conserve power.

What happens when you connect to this idle instance is that we now create a new hardware encoder, which will sit idle too until it receives the first frame from dwm.exe, which happens when the window leaves its idle state.

This can happen either by you interacting with the window by, let's say, moving the mouse, or by waiting a minute for dwm.exe to force-invalidate the window itself.

This is all standard Windows behavior, but we don't really see this on physical monitors because the stream of frames is uninterrupted, while Duo's monitor swapchain frames don't really become visible until the hardware encoder gets their hands on them, which causes this odd black-screen gap in the first place.

We might be able to mitigate this to an extend by caching the last frame's NT handle in RdpIddCapture.dll and thus ensuring newly allocated hardware encoder instances will always have at least one frame to read no matter when they get instanced.

The reason why older Duo versions didn't suffer from this issue was because we used a different capture method, or rather, a different method of transference of data.

That older method had its own drawbacks though, including a rather costly, in comparison, overhead that made 4K streaming somewhat difficult.

Either way. Keep me posted on your results.

As for making the suspend pausing an option, I see no reason why it should be optional.

Is there a downside to this that I'm unaware of that would warrant making this an option?

**Comment by Black-Seraph** [comment]
@bigjam3 Keep us posted with your results.

I will leave this issue open until then.

**Comment by kopiezzo** [comment]
I can confirm that in the new version, there are no longer any issues related to Nvidia crashes. However, I still experience crashes with kernelbase.dll and sunshine as mentioned above.

> As for making the suspend pausing an option, I see no reason why it should be optional.
Is there a downside to this that I'm unaware of that would warrant making this an option?

I was considering leaving HAGS disabled to avoid crashes in exchange for faster session connections, but I think I'll pass on that.
